In [2]:
import tensorflow as tf

In [18]:
a=tf.constant(2)
a

<tf.Tensor 'Const_8:0' shape=() dtype=int32>

In [5]:
a=tf.constant(2)
a

<tf.Tensor 'Const_1:0' shape=() dtype=int32>

In [6]:
b=tf.constant(3)
b

<tf.Tensor 'Const_2:0' shape=() dtype=int32>

In [7]:
c=a+b
c

<tf.Tensor 'add:0' shape=() dtype=int32>

In [9]:
s=tf.Session()
s.run(c)

5

In [10]:
a1=tf.constant([[3,3]])
a2=tf.constant([[1],[2]])
c=tf.matmul(a1,a2)

In [11]:
s.run(c)

array([[9]])

In [14]:
with tf.Session() as s:
    print(c.eval())
    print(s.run(c))

[[9]]
[[9]]


In [20]:
v1=tf.Variable(100)
v2=tf.Variable(33)
sum=v1+v2
s=tf.Session()
s.run(tf.global_variables_initializer())
s.run(sum)

133

In [21]:
e=v1.assign(122)
s.run(e)

122

In [22]:
s.run(v1)

122

In [24]:
x=tf.placeholder(tf.int32)
y=x*tf.constant(3)
s.run(y,feed_dict={x:4})

12

In [25]:
x=tf.placeholder(tf.int32)
y=x*tf.constant(3)
s.run(y,feed_dict={x:[[2,3],[1,2]]})

array([[6, 9],
       [3, 6]])

In [30]:
z=tf.placeholder(tf.int32,shape=(1,1))
y=z*tf.constant(3)
s.run(y,feed_dict={z:[[4]]})

array([[12]])